
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed3;

	private global::Gtk.Entry txt_message;

	private global::Gtk.Button buttonEvent;

	private global::Gtk.Label labelNameTitle;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Hello World");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.txt_message = new global::Gtk.Entry();
		this.txt_message.CanFocus = true;
		this.txt_message.Name = "txt_message";
		this.txt_message.IsEditable = true;
		this.txt_message.InvisibleChar = '•';
		this.fixed3.Add(this.txt_message);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txt_message]));
		w1.X = 30;
		w1.Y = 177;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.buttonEvent = new global::Gtk.Button();
		this.buttonEvent.CanFocus = true;
		this.buttonEvent.Name = "buttonEvent";
		this.buttonEvent.UseUnderline = true;
		this.buttonEvent.BorderWidth = ((uint)(5));
		this.buttonEvent.Label = global::Mono.Unix.Catalog.GetString("Press Here");
		this.fixed3.Add(this.buttonEvent);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.buttonEvent]));
		w2.X = 252;
		w2.Y = 169;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.labelNameTitle = new global::Gtk.Label();
		this.labelNameTitle.Name = "labelNameTitle";
		this.labelNameTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Write Your Name");
		this.fixed3.Add(this.labelNameTitle);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.labelNameTitle]));
		w3.X = 140;
		w3.Y = 73;
		this.Add(this.fixed3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 407;
		this.DefaultHeight = 296;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonEvent.Clicked += new global::System.EventHandler(this.OnButtonEventClicked);
	}
}
